---
- name: "Reset Kubernetes"
  shell: echo $(kubeadm reset && echo 'true') 

- name: "Remove docker images" 
  shell: echo $(docker rmi --force $(docker images --all -q) && echo 'true')
  become: true

- name: "apt-get update"
  apt:
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: "apt-get purge packages"
  apt:
    name: ['kubelet', 'kubeadm', 'kubectl', 'docker-ce']
    state: absent
    purge: yes
    autoremove: yes
    force: yes

- name: "Remove pod logging"
  file:
    path: "{{ item }}"
    state: absent
  become: True
  loop:
    - /etc/kubernetes
    - /var/log/pods
    - /var/log/containers
    - /var/lib/kubelet


- name: Reboot
  reboot:
    reboot_timeout: 120
